CREATE TABLE IF NOT EXISTS LoginHistory (
    LoginHistoryId INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Success BOOLEAN NOT NULL,
    AttemptedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    IpAddress VARCHAR(45) NULL
);